[package]
name = "apex-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
log = "0.4.21"
pretty_env_logger = "0.5.0"
color-eyre = "0.6.3"

winit = "0.29.15"
egui-wgpu = "0.27.2"
egui_extras = { version = "0.27.2", features = ["all_loaders"] }
egui = "0.27.2"

rodio = "0.18.0"

pollster = { version = "0.3.0", features = ["macro"] }
glam = { version = "0.27.0", features = ["bytemuck", "serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
bytemuck = "1.15.0"
image = { version = "*", features = ["jpeg", "png"] }
instant = "0.1.12"
fxhash = "0.2.1"
indexmap = "2.2.6"
tap = "1.0.1"
cfg-if = "1.0.0"
intbits = "0.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = "0.19.4"
egui-winit = "0.27.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.19.4", features = ["webgl"] }
egui-winit = { version = "0.27.2", features = [], default-features = false}

console_error_panic_hook = "0.1.6"
console_log = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
  "Document",
  "Window",
  "Element",
]}

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
