name: Build WASM

on:
  workflow_call:

env:
  target: "wasm32-unknown-unknown"

jobs:
  build_wasm:
    name: Build WASM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ env.target }}
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ env.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ env.target }}
      - name: Install WASM
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build WASM
        working-directory: ./apex-client
        run: wasm-pack build --release
#      - name: Deploy WASM
#        uses: peaceiris/actions-gh-pages@v3
#        if: github.ref == 'refs/heads/main'
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./language/documentation/book/book
