name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install alsa
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install librust-alsa-sys-dev
      - name: Install aarch64 toolchain
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install gcc-aarch64-linux-gnu
          export PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu
      - name: Build
        env:
          PKG_CONFIG_SYSROOT_DIR: ${{ env.PKG_CONFIG_SYSROOT_DIR }}
        run: cargo make build --release --target ${{ matrix.target }}
      - name: Copy assets
        run: |
          cp -r assets target/${{ matrix.target }}/release
      - name: Upload
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/apex-client
            target/${{ matrix.target }}/release/apex-client.exe
            target/${{ matrix.target }}/release/assets

