name: Build Linux

on:
  workflow_call:

jobs:
  build_android:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev
          version: 1.0
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build --release
      - name: DEBUG show artifacts
        run: |
          ls -la target
          du .

#      - name: Upload artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: my-artifact
#          path: |
#            target
