name: Check and lint

on:
  workflow_call:

env:
  target: "x86_64-unknown-linux-gnu"

jobs:
  check:
    runs-on: ubuntu-latest
    name: Analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev
          version: 1.0
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ env.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ env.target }}
      - name: Run cargo check
        uses: qRoC/cargo-actions@v1
        with:
          command: check
          toolchain: nightly
          args: --locked --verbose --target ${{ env.target }} --package apex-client
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run cargo fmt code style
        uses: qRoC/cargo-actions@v1
        with:
          command: fmt
          toolchain: nightly
          args: --all -- --check
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run cargo clippy
        uses: qRoC/cargo-actions@v1
        with:
          command: clippy
          toolchain: nightly
          args: --all-features --all-targets -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run cargo audit
        uses: qRoC/cargo-actions@v1
        with:
          command: audit
          toolchain: nightly

